import { Layout } from "@components/Layout";
import { GlobalStyle } from "@styles/global";
import theme from "@styles/global/theme";
import type { AppProps } from "next/app";
import Head from "next/head";
import { ThemeProvider } from "styled-components";
import { FavoritesProvider } from "../context/FavoritesContext";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
      </Head>
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <FavoritesProvider>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </FavoritesProvider>
      </ThemeProvider>
    </>
  );
}
