import Head from "next/head";
import { Inter } from "@next/font/google";
import { GlobalStyle } from "@styles/global";
import { ThemeProvider } from "styled-components";
import theme from "@styles/global/theme";
import { Layout } from "@components/Layout";
import { App } from "@components/App";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Fiscaliza</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
      </Head>
      <GlobalStyle />
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <Layout>
          <App />
        </Layout>
      </ThemeProvider>
    </>
  );
}
